title: AHA wiki page
remote_theme: sighingnow/jekyll-gitbook
baseurl: /aha-wiki-page
toc:
  enabled: true
  h_min: 1
  h_max: 3
collections:
  posts1:
    output: true
    permalink: /:collection/:title
  posts2:
    output: true
    permalink: /:collection/:title
