title: AHA wiki page
remote_theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
  h_min: 1
  h_max: 1
collections:
  pages:
    output: true
    permalink: /:collection/:title
    
    order:
      - aha_commands
      - h2h_files
      - design_flow.md
      - design_files.md
      - pnr.md
      - lake.md
      - lake_repo.md
      - waveform_debugging.md
      - lake_waveform.md
