title: AHA wiki page
remote_theme: sighingnow/jekyll-gitbook
url: 'https://paying4529.github.io'
baseurl: '/aha-wiki-page'
rss: RSS
toc:
  enabled: true
  h_min: 1
  h_max: 3
permalink: /:categories/:year-:month-:day-:title:output_ext
collections:
  pages:
    output: true
    permalink: /:collection/:path/
