title: AHA wiki page
remote_theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
  h_min: 1
  h_max: 3
collections:
  posts1:
    output: true
    permalink: /:collection/:title
  posts2:
    output: true
    permalink: /:collection/:title
    order:
      - aha_commands.md
      - h2h_files.md
      - design_flow.md
      - design_files.md
      - pnr.md
      - lake.md
      - lake_repo.md
      - waveform_debugging.md
      - lake_waveform.md
